"""
Each new term in the Fibonacci sequence is generated by adding the
previous two terms. By starting with 1 and 2, the first 10 terms will
be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do
not exceed four million, find the sum of the even-valued terms.
"""

def fibonacci_even(n):
    """
    Compute the sum of even fibonnaci terms 
    less than n
    """
    term_n   = 1
    term_n_1 = 2
    sum_fib  = 0

    while (term_n_1 < n):
        if (term_n_1 % 2 == 0):
            sum_fib += term_n_1

        # Computing the next term
        term_n, term_n_1 = term_n_1, term_n + term_n_1

    return sum_fib

if __name__ == '__main__':
    res = fibonacci_even(4000000)
    print(res)
